### ISSUE TITLE
Adding more kmk features

### ISSUE THREAD

**Issue by dreffii** [JanLunge/pog#20]
Hello there, I'm new to kmk keyboards. I found out there are more features from kmk. I would like to know if there anyway I can integrate more features to keyboard that flash with pog. Those features such as Rapidfire, Steno, etc. Thanks.

**Comment by JanLunge** [comment]
right now you can add them manually to the kb.py file on your keyboard, you can take a look at how it is done for the other features in there. the feature flags that toggle the enabled state are in the kbFeatures key in the pog.json. but for simple thing you can just enable it on your keyboard by doing no if check before. 
over time these will also be added to pog

**Comment by dreffii** [comment]
Thanks so much it works :D
