### ISSUE TITLE
send_string is not defined

### ISSUE THREAD

**Issue by kokoparkletal** [JanLunge/pog#34]
Hi, 

I'm trying to add a string key on version 1.4.5, but after saving I get the error "send_string is not defined" via serial.

`code.py output:
starting keyboard Corne Choc Mini L (01J5QZFK6KYXXC8YMMJ6T7RRF7)
split with 1 pin
Traceback (most recent call last):
  File "code.py", line 21, in <module>
  File "keymap.py", line 10, in <module>
NameError: name 'send_string' is not defined`

Thanks for you work

**Comment by JanLunge** [comment]
They now changed the send_string to the macro feature in kmk some refactoring is needed to use the new format, pog already works with it but only the newer versions and the firmware on the pico needs to be up to date as well

**Comment by kokoparkletal** [comment]
I installed kmk with pog last week (I can check version right now) and CP are 9.2.0-alpha.2351 version

**Comment by JanLunge** [comment]
Everything is now ported to macros, just cleaning up issues a bit late
