### ISSUE TITLE
issue with keymap.py somehow corrupting

### ISSUE THREAD

**Issue by StefanTheFork** [JanLunge/pog#35]
Sometimes my keyboard dies and i have to set up pog again, and when i drag the files out of the circuitpy drive and to my desktop keymap.py is empty
this has been happening for the last 2-3 days

**Comment by StefanTheFork** [comment]
by dies i mean it just doesnt respond to any keypress and if i replug it it still wont record any keypress even after i wait 5-10 seconds

**Comment by StefanTheFork** [comment]
okay new issue, when i save my keymap after editing it, the keyboard does save it but needs to be replugged 2 times and sometimes dies and doesnt register keypresses....... im very confused as to why this is happening ;/
and it also dies after around 2 minutes of being plugged in

**Comment by JanLunge** [comment]
Everytime the file corrupts for me it was an issue with my operating system. Mac os for example had a lot of trouble with the way the filesystem works and broke on multiple updates. Its likely not an issue with pog when the file on the drive is empty or bot readable, maybe wiping the controller with the flash nuke uf2 file could fix this issue

**Comment by JanLunge** [comment]
For all other problems check the repl for the error codes

**Comment by StefanTheFork** [comment]
ill try to reflash circuit python and reinstall pog. wish me luck lol

**Comment by StefanTheFork** [comment]
> Everytime the file corrupts for me it was an issue with my operating system
hmm ill try it on linux and see if it still corrupts.....

**Comment by StefanTheFork** [comment]
it was all a problem with windows and circuit python
i rebooted and then reflashed the keeb and it works perfectly. idk how i didnt think of that tbh
