### ISSUE TITLE
Keyboard Layout Editor rendering issue

### ISSUE THREAD

**Issue by chatelao** [JanLunge/pog#38]
I get this layout editor missalignement. What files do you need to fix it?

![image](https://github.com/user-attachments/assets/3e0bb599-7a40-46c3-9a51-2626441a9601)

**Comment by JanLunge** [comment]
Theree seems to be an issue with the height calculations when the keyboard is taller than wide on startup. For now you can resize the window a bit and it should update the keyboard size to fit

**Comment by JanLunge** [comment]
I was able to reproduce the issue so I don't need any more info to fix it thank you for the issue creation.

**Comment by chatelao** [comment]
Danke für die prompte Antwort ♥️

**Comment by JanLunge** [comment]
should be fixed in the next release
