### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by kdb424** [JanLunge/pog#4]
I noticed this project doesn't have a license to use the code. Is this code going to get a license at some point to be used, or just here for personal storage? Love the efforts, and hope to see this get some sort of open license in the future!

**Comment by rayererer** [comment]
A [LICENSE](https://github.com/JanLunge/pog/blob/main/LICENSE) has since been added in commit 880a582. So I suppose this issue can be closed.

**Comment by JanLunge** [comment]
Yes MIT license has been added.
Seems I had Notifications for Issues and PRs off my bad fixed this now.
