### ISSUE TITLE
pico brick after click on update kmk in the firmware tab

### ISSUE THREAD

**Issue by neneko21** [JanLunge/pog#46]
i accidentally click on the update kmk in the firmware tab now i cant press anything even after doing the flash nuke the coord finder just didnt output anything

**Comment by JanLunge** [comment]
yes the current kmk version has some changes that break pog, I am working on a way to lock to known working versions of kmk but this has been a bit difficult

**Comment by neneko21** [comment]
so is there any stop gap solution currently

**Comment by neneko21** [comment]
somehow after like a billion of flash nuke i got it to work again many thank for the project
