### ISSUE TITLE
Install KMK option just sits at downloading forever

### ISSUE THREAD

**Issue by NoahSparks** [JanLunge/pog#49]
Install KMK option just sits at downloading forever

**Comment by JanLunge** [comment]
I heard that as this is downloading from github some antivirus tools prevent the download you could check that to exclude pog or install kmk manually. I havent seen this issue on my machines so its hard to test for me.

**Comment by NoahSparks** [comment]
> I heard that as this is downloading from github some antivirus tools prevent the download you could check that to exclude pog or install kmk manually. I havent seen this issue on my machines so its hard to test for me.

Yeah, I will test when I get home. I'm just using windows defender.

**Comment by RasmusB** [comment]
This is happening to me as well. Windows 11, no antivirus running except for Windows defender. Other apps such as vscode and git have no issue downloading from github. How can I troubleshoot this?

**Comment by JanLunge** [comment]
should be fixed by https://github.com/JanLunge/pog/releases/tag/v1.8.0 v1.8.0
