### ISSUE TITLE
Unable to change keycodes (Windows 11)

### ISSUE THREAD

**Issue by TylerPritts** [JanLunge/pog#7]
Hi I am experimenting with a 1x4 but cannot change any keycode. Am I doing something wrong or is this a bug? The setup for the firmware went fine and had no issues with that. I can still edit manually by using VSCode and that will work, but Pog doesn't read it.

![image_2024-01-17_032642928](https://github.com/JanLunge/pog/assets/68491736/380088e9-5643-4e98-9c21-135df1703b98)

**Comment by JanLunge** [comment]
likely it is missing the keyIndex in the keyboard Layout tab, this connects what you have setup in the coordmap to where each key is on your keyboard so pog can lookup where to display the keymap and assign them accordingly. I should add this as a validity check when editing as this is a common problem.

**Comment by JanLunge** [comment]
seemed to be a bug with the coord map saving, make sure your keyboard layout has the keys numbered starting from 0 based on your coodmap order v1.2.2 should have this saving problem resolved
